spring:
  application:
    name: sample-api

  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: local_user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
