openapi: 3.0.0
info:
    title: app-sample
    version: 1.0.0

paths:
    /users/{id}:
        $ref: "./paths/users.yml#/getUserById"

components:
    schemas:
        User:
            $ref: "./schemas/user.yml#/User"
