openapi: 3.0.0
info:
    title: app-sample
    version: 1.0.0

paths:
    /users/{id}:
        $ref: "./paths/user/index.yml"

components:
    schemas:
        User:
            $ref: "./schemas/user/index.yml"
