version: "3.8"
services:
  db:
    image: "postgres:15"
    container_name: "app_db"
    restart: always
    environment:
      POSTGRES_USER: "local_user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "app_db"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  openapi-generator:
    image: "openapitools/openapi-generator-cli:v7.7.0"
    container_name: "openapi-generator"
    working_dir: "/generator"
    volumes:
      - ../openapi:/generator # OpenAPI 定義ファイル
      # OpenAPI Codegenの出力先
      # host:containerの形式でcodegenがsrc/から出力される為、host側はdemo/までにする
      - ../backend/demo:/local/backend

  swagger-ui:
    image: "swaggerapi/swagger-ui"
    container_name: "swagger-ui"
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: "/openapi/openapi.yml"
    volumes:
      - ../openapi:/openapi:ro

volumes:
  db-data: